### ISSUE TITLE
gitjk gives invalid advice for undoing `git checkout <tree-ish> <paths>…`

### ISSUE THREAD

**Issue by roryokane** [mapmeld/gitjk#13]
I was wondering if there was any way to undo this command I ran:

```
git checkout HEAD src/someFile.js src/anotherFile.js
```

I piped it into `gitjk_cmd`, but this was the output:

```
git checkout moved you into a different branch of the repo. You can checkout any branch by name, or checkout the last one using -
git checkout -
```

This explanation is incorrect. With these arguments, `git checkout` overwrote the two files in my working directory I specified with their versions at the given commit, in this case `HEAD`. The command didn’t make me switch branches.

With this input, gitjk should tell me how to undo my checkout of those files if possible, or at least recognize the situation and tell me “there is no way to recover the overwritten files”.

**Comment by mapmeld** [comment]
just published a new version and added test to confirm!

unfortunately I don't think that you can recover changes to files since the last commit :-(
