### ISSUE TITLE
'git pull' help text might be wrong

### ISSUE THREAD

**Issue by alexpear** [mapmeld/gitjk#14]
undo = 'git reset --hard HEAD^'

I think this will be insufficient if the pull or merge introduced multiple new commits.

**Comment by mapmeld** [comment]
what do you think would be a good fix?

**Comment by alexpear** [comment]
Basically something like:
'This merged commits from another branch (local or remote) into your current branch. Use 'git reset --hard origin/<branchname>' to undo.' 
(assuming their remote is named origin)

OR

'This merged commits from another branch (local or remote) into your current branch. Use `git log` to see what has been added, and `git reset --hard <desiredcommit>` to undo.'
